[package]
name = "nebulacrypto"
version = "0.2.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "full"] }
sled = "0.34"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
ed25519-dalek = { version = "2", features = ["rand_core"]}
rand = "0.8"
tokio-stream = "0.1.17"
quinn = "0.10"
tokio-rustls = "0.24"
rcgen = "0.10"
chrono = "0.4.39"
sha2 = "0.10.8"


[dev-dependencies]
assert_matches = "1.5"
